version: '2'  
services:  
  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "8000:8000"
    volumes:
      - ./foss4g:/src
      - ./nginx/sites-enabled:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    container_name: dg01
    command: bash -c "gunicorn foss4g.wsgi -b 0.0.0.0:8000"
    volumes:
      - ./foss4g:/src
    expose:
      - "8000"
